"""documento actualizacion 2

Revision ID: 0a80ee0efe15
Revises: e639f47207f5
Create Date: 2026-02-25 12:20:32.641138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a80ee0efe15'
down_revision = 'e639f47207f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_column('tipo_archivo')

    with op.batch_alter_table('documento_colindante', schema=None) as batch_op:
        batch_op.alter_column('tipo_documento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('nombre_archivo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.drop_column('tipo_archivo')
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_colindante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_archivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('nombre_archivo',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_archivo', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
