"""juridica campos a Text

Revision ID: 1a12b71c7afb
Revises: 93756f479494
Create Date: 2026-02-25 10:54:00.514118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a12b71c7afb'
down_revision = '93756f479494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catastral', schema=None) as batch_op:
        batch_op.alter_column('numero_predial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('fmi_r1_r2',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_r1_r2',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('propietario',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('cedula_propietario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('referencia_catastral',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.alter_column('cardinalidad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('fmi_colindante',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('numero_predial_colindante',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_colindante',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('id_ant',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('tipo_colindante',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('documento_origen_colindante',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('propietario_inicial_colindante',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('propietario_actual_vur_colindante',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('plano_colindante',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.alter_column('ruta_relativa',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
        batch_op.alter_column('tipo_archivo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('juridica', schema=None) as batch_op:
        batch_op.alter_column('documento_origen_inmueble',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_origen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('adjudicatario_inicial',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('referencia_catastral_vur',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('tipo_instrumento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('tipo_predio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('estado_folio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_actual',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('plano_juridica',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('localizacion', schema=None) as batch_op:
        batch_op.alter_column('dpto_espacial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('municipio_espacial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('vereda_espacial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('municipio_vur',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('dpto_vur',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('vereda_vur',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.alter_column('nombre_predio_vur',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.alter_column('nombre_predio_vur',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('localizacion', schema=None) as batch_op:
        batch_op.alter_column('vereda_vur',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('dpto_vur',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('municipio_vur',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('vereda_espacial',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('municipio_espacial',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('dpto_espacial',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('juridica', schema=None) as batch_op:
        batch_op.alter_column('plano_juridica',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_actual',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('estado_folio',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipo_predio',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipo_instrumento',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('referencia_catastral_vur',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('adjudicatario_inicial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_origen',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('documento_origen_inmueble',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.alter_column('tipo_archivo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('ruta_relativa',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.alter_column('plano_colindante',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('propietario_actual_vur_colindante',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('propietario_inicial_colindante',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('documento_origen_colindante',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('tipo_colindante',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('id_ant',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_colindante',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('numero_predial_colindante',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('fmi_colindante',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('cardinalidad',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('catastral', schema=None) as batch_op:
        batch_op.alter_column('referencia_catastral',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('cedula_propietario',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('propietario',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nombre_predio_r1_r2',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('fmi_r1_r2',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('numero_predial',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
