"""Agregar campo area_terreno_ha_r1r2 a catastral

Revision ID: 7d3d206b32c5
Revises: 926f156a0175
Create Date: 2026-04-30 13:21:07.509340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3d206b32c5'
down_revision = '926f156a0175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catastral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_terreno_ha_r1r2', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catastral', schema=None) as batch_op:
        batch_op.drop_column('area_terreno_ha_r1r2')

    # ### end Alembic commands ###
