"""Cambiar fuente_validacion a Text en colindante

Revision ID: 926f156a0175
Revises: 9db39e2295f6
Create Date: 2026-04-21 15:53:10.848887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926f156a0175'
down_revision = '9db39e2295f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.alter_column('fuente_validacion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.alter_column('fuente_validacion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
