"""esquema inicial completo

Revision ID: 93756f479494
Revises: 
Create Date: 2026-02-23 21:12:02.895180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93756f479494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predio',
    sa.Column('id_predio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('fmi', sa.String(length=100), nullable=False),
    sa.Column('propietario_vur', sa.String(length=2000), nullable=True),
    sa.Column('numero_documento_propietario_vur', sa.String(length=2000), nullable=True),
    sa.Column('nombre_predio_vur', sa.String(length=200), nullable=True),
    sa.Column('area_vur', sa.Float(), nullable=True),
    sa.Column('es_derivado', sa.Boolean(), nullable=True),
    sa.Column('id_predio_matriz', sa.String(length=100), nullable=True),
    sa.Column('tiene_derivadas', sa.Boolean(), nullable=True),
    sa.Column('derivadas_ids', sa.String(length=5000), nullable=True),
    sa.Column('proceso_englobe_desenglobe', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_predio'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catastral',
    sa.Column('id_catastral', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('numero_predial', sa.String(length=100), nullable=True),
    sa.Column('fmi_r1_r2', sa.String(length=100), nullable=True),
    sa.Column('nombre_predio_r1_r2', sa.String(length=200), nullable=True),
    sa.Column('propietario', sa.String(length=200), nullable=True),
    sa.Column('cedula_propietario', sa.String(length=50), nullable=True),
    sa.Column('area_terreno_ha', sa.Float(), nullable=True),
    sa.Column('destino_economico', sa.String(length=100), nullable=True),
    sa.Column('referencia_catastral', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.PrimaryKeyConstraint('id_catastral')
    )
    op.create_table('colindante',
    sa.Column('id_colindante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('numero_colindante', sa.Integer(), nullable=True),
    sa.Column('cardinalidad', sa.String(length=50), nullable=True),
    sa.Column('fmi_colindante', sa.String(length=100), nullable=True),
    sa.Column('numero_predial_colindante', sa.String(length=100), nullable=True),
    sa.Column('nombre_predio_colindante', sa.String(length=200), nullable=True),
    sa.Column('id_ant', sa.String(length=100), nullable=True),
    sa.Column('tiene_levantamiento', sa.Boolean(), nullable=True),
    sa.Column('tipo_colindante', sa.String(length=100), nullable=True),
    sa.Column('documento_origen_colindante', sa.String(length=200), nullable=True),
    sa.Column('propietario_inicial_colindante', sa.String(length=200), nullable=True),
    sa.Column('propietario_actual_vur_colindante', sa.String(length=200), nullable=True),
    sa.Column('plano_colindante', sa.String(length=200), nullable=True),
    sa.Column('necesario_validar_campo', sa.Boolean(), nullable=True),
    sa.Column('observacion_colindante', sa.Text(), nullable=True),
    sa.Column('colindante_primera_anotacion', sa.Text(), nullable=True),
    sa.Column('colindante_ultima_anotacion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.PrimaryKeyConstraint('id_colindante')
    )
    op.create_table('documento',
    sa.Column('id_documento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=True),
    sa.Column('tamaño_bytes', sa.Float(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('juridica',
    sa.Column('id_juridica', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('documento_origen_inmueble', sa.String(length=200), nullable=True),
    sa.Column('area_juridica_ha', sa.Float(), nullable=True),
    sa.Column('nombre_predio_origen', sa.String(length=200), nullable=True),
    sa.Column('adjudicatario_inicial', sa.String(length=200), nullable=True),
    sa.Column('referencia_catastral_vur', sa.String(length=200), nullable=True),
    sa.Column('nupre', sa.String(length=100), nullable=True),
    sa.Column('documento_primera_anotacion', sa.Text(), nullable=True),
    sa.Column('documento_ultima_anotacion', sa.Text(), nullable=True),
    sa.Column('fecha_apertura_folio', sa.String(length=20), nullable=True),
    sa.Column('tipo_instrumento', sa.String(length=100), nullable=True),
    sa.Column('fecha_instrumento', sa.String(length=20), nullable=True),
    sa.Column('tipo_predio', sa.String(length=100), nullable=True),
    sa.Column('estado_folio', sa.String(length=100), nullable=True),
    sa.Column('complementaciones', sa.Text(), nullable=True),
    sa.Column('cabida_linderos', sa.Text(), nullable=True),
    sa.Column('salvedades', sa.Text(), nullable=True),
    sa.Column('vida_juridica', sa.Text(), nullable=True),
    sa.Column('nombre_predio_actual', sa.String(length=200), nullable=True),
    sa.Column('plano_juridica', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.PrimaryKeyConstraint('id_juridica')
    )
    op.create_table('localizacion',
    sa.Column('id_localizacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_predio', sa.Integer(), nullable=False),
    sa.Column('dpto_espacial', sa.String(length=100), nullable=True),
    sa.Column('municipio_espacial', sa.String(length=100), nullable=True),
    sa.Column('vereda_espacial', sa.String(length=100), nullable=True),
    sa.Column('tiene_municipio_diferente_vur', sa.Boolean(), nullable=True),
    sa.Column('municipio_vur', sa.String(length=100), nullable=True),
    sa.Column('dpto_vur', sa.String(length=100), nullable=True),
    sa.Column('vereda_vur', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_predio'], ['predio.id_predio'], ),
    sa.PrimaryKeyConstraint('id_localizacion')
    )
    op.create_table('documento_colindante',
    sa.Column('id_doc_colindante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_colindante', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=5000), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=True),
    sa.Column('tamaño_bytes', sa.Float(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_colindante'], ['colindante.id_colindante'], ),
    sa.PrimaryKeyConstraint('id_doc_colindante')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_colindante')
    op.drop_table('localizacion')
    op.drop_table('juridica')
    op.drop_table('documento')
    op.drop_table('colindante')
    op.drop_table('catastral')
    op.drop_table('predio')
    # ### end Alembic commands ###
