"""Agregar tipo_gestion en Predio

Revision ID: 98860958b32e
Revises: b23b19417597
Create Date: 2026-03-17 01:59:06.461865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98860958b32e'
down_revision = 'b23b19417597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_derivado_colindante', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('id_predio_matriz_colindante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tiene_derivadas_colindante', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('derivadas_ids_colindante', sa.String(length=5000), nullable=True))

    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_gestion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.drop_column('tipo_gestion')

    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.drop_column('derivadas_ids_colindante')
        batch_op.drop_column('tiene_derivadas_colindante')
        batch_op.drop_column('id_predio_matriz_colindante')
        batch_op.drop_column('es_derivado_colindante')

    # ### end Alembic commands ###
