"""Agregar cas

Revision ID: 9db39e2295f6
Revises: 98860958b32e
Create Date: 2026-03-17 03:01:07.435911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db39e2295f6'
down_revision = '98860958b32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juridica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juridica', schema=None) as batch_op:
        batch_op.drop_column('cas')

    # ### end Alembic commands ###
