"""nuevos campos colindante

Revision ID: b23b19417597
Revises: b5451142349f
Create Date: 2026-03-08 20:37:02.779344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23b19417597'
down_revision = 'b5451142349f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vereda_colindante', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('municipio_colindante', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('departamento_colindante', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('estado_validacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuente_validacion', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('requiere_verificacion_campo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('es_presunto_baldio', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colindante', schema=None) as batch_op:
        batch_op.drop_column('es_presunto_baldio')
        batch_op.drop_column('requiere_verificacion_campo')
        batch_op.drop_column('fuente_validacion')
        batch_op.drop_column('estado_validacion')
        batch_op.drop_column('departamento_colindante')
        batch_op.drop_column('municipio_colindante')
        batch_op.drop_column('vereda_colindante')

    # ### end Alembic commands ###
