"""documento actualizacion 3

Revision ID: b5451142349f
Revises: 0a80ee0efe15
Create Date: 2026-02-25 12:21:12.683790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5451142349f'
down_revision = '0a80ee0efe15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
