"""Agregar campo area_final_gc a predio

Revision ID: f2f52b745e37
Revises: 7d3d206b32c5
Create Date: 2026-05-11 20:01:59.482511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f52b745e37'
down_revision = '7d3d206b32c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_final_gc', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predio', schema=None) as batch_op:
        batch_op.drop_column('area_final_gc')

    # ### end Alembic commands ###
